---
# tasks file for vim
- name: Create first files
  file:
    dest: /home/ubuntu/temp/firstfile.txt
    state: touch
  tags:
    - create_fileOne

- name: Create 2nd file
  file:
    dest: /home/ubuntu/temp/secfile.txt
    state: touch
  tags:
    - create_file2



